templates/ASP5Bootstrap/Pages/Components/HeaderLinks/HeaderLinksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace IVC_WebApp.Pages.Components
{
    public class HeaderLinksViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(List<HeaderLinkModel> headerLinks)
        {
            return await Task.FromResult((IViewComponentResult)View("HeaderLinks", headerLinks));
        }
    }
}

templates/ASP5Bootstrap/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace IVC_WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

templates/ASP5Bootstrap/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace IVC_WebApp.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

templates/ASP5Bootstrap/Pages/Components/HeaderLinks/HeaderLinks.cshtml
@using IVC_WebApp.Pages.Components
@model List<HeaderLinkModel>

@if(Model.Any())
{
    <!-- Hamburger Button -->
    <button class="navbar-toggler p-1" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon fs-6"></span>
    </button>

    <div class="collapse navbar-collapse mx-3" id="navbarNav">
        <ul class="navbar-nav gap-3">
            @foreach (var headerLink in Model)
            {
                <li>
                    <a href="@headerLink.Url" class="nav-link link-secondary">
                        @if(!string.IsNullOrEmpty(headerLink.IconName))
                        {
                            <span><i class="bi bi-@headerLink.IconName"></i></span>
                        }

                        <span>@headerLink.Title</span>
                    </a>
                </li>
            }
        </ul>
    </div>
}

templates/ASP5Bootstrap/Pages/Index.cshtml
@page
@model IVC_WebApp.Pages.IndexModel
@{
  ViewData["Title"] = "خانه";
}

templates/ASP5Bootstrap/Pages/Shared/_Brand.cshtml
<a class="navbar-brand d-flex gap-2" href="/">
    <img src="~/img/logo.svg" alt="WebApp Logo" width="24" height="24">
    <h5>اپلیکیشن</h5>
</a>

templates/ASP5Bootstrap/Pages/Shared/_Footer.cshtml
<footer class="footer container-fluid d-flex justify-content-center border-top p-3">
    <span class="text-muted" dir="ltr">&copy; @DateTime.Now.Year</span>
</footer>

templates/ASP5Bootstrap/Pages/Shared/_Header.cshtml
<header class="sticky-top">
    <nav class="navbar navbar-light navbar-expand-sm border-bottom p-3">
        <div class="container-fluid justify-content-md-start justify-content-sm-between">
            <partial name="_Brand" />
            <partial name="_Menu" />
        </div>
    </nav>
</header>

templates/ASP5Bootstrap/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <title>@ViewData["Title"] - اپلیکیشن</title>

    <!-- Meta/SEO Tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="robots" content="index, follow" />

    <!-- Fav Icons -->
    <link rel="shortcut icon" href="~/favicon.ico" />

    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.rtl.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/vazir-font/font-face.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/set.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <partial name="_Header" />

    <main class="container-fluid p-3 my-3" role="main">
        @RenderBody()
    </main>

    <partial name="_Footer" />

    <script src="~/lib/jquery/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

templates/ASP5Bootstrap/Pages/Shared/_Menu.cshtml
@using IVC_WebApp.Pages.Components

@{
    var headerLinks = new List<HeaderLinkModel>()
    {
        new HeaderLinkModel{Url="/Index",Title="خانه"},
        new HeaderLinkModel{Url="/Link1",Title="لینک 1"}
    };
}

@await Component.InvokeAsync("HeaderLinks", headerLinks)